### ISSUE TITLE
The game slows down when too many tiles are revealed

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#198]
Meta issue for performance and responsiveness issues during state updates

the larger the state gets the more laggy/stuttery the game gets.

tracked by:

```[tasklist]
### Tasks
- [ ] https://github.com/playmint/ds/issues/360
- [ ] https://github.com/playmint/ds/issues/361
- [ ] https://github.com/playmint/ds/issues/362
```

**Comment by chrisfarms** [comment]
resolved by issues in the task list

biggest performance issue remaining is the query performance from the indexer, but this is because we are requesting too much stuff at once and the solution there is Zones which are out of scope for this milestone
